### ISSUE TITLE
Add basic cookie policy

### ISSUE THREAD

**Issue by mattwells19** [lvl-mattwells/DevsPlayingPoker#78]
- Add a cookie policy page that explains how DPP uses cookies
    - Resource: https://termly.io/resources/templates/cookie-policy-template/#getting-user-consent-for-your-cookies-policy
 - Add bottom banner that briefly summarizes cookie use on the site. Since DPP only uses a session cookie which is considered "essential" no consent is actually needed from the user.
    - Resource: https://termly.io/resources/articles/gdpr-cookie-consent-examples/#what-is-implied-consent-and-does-it-comply-with-the-gdpr

**Comment by lvl-mattwells** [comment]
Since we're not tracking users and the session cookie we use is essential for the app to work, just gonna forgo this for now.

If you're interested in learning more about how DPP uses cookies going forward please reference the cookie wiki: https://github.com/lvl-mattwells/DevsPlayingPoker/wiki/DPP's-use-of-cookies
